### ISSUE TITLE
Best way to run on a cluster with qsub?

### ISSUE THREAD

**Issue by mick-d** [GGiecold/Concurrent_AP#1]
This is a very useful package. I am now assessing what would be the best way to run it on a cluster with qsub (open MPI, etc.)? Any suggestion would be great.

**Comment by GGiecold-zz** [comment]
Thank you for your interest.

While Concurrent_AP was designed to run multiple processes from single
machine, it should be possible to modify the existing code and get
clusters of computers to perform affinity propagation clustering. The
various worker classes existent in Concurrent_AP should be of help in
this regard. You probably wouldn't have to bring many alterations; one I
can foresee has to do with the locking of HDF5 file access.
HDF5 data structures are key to Concurrent_AP's ability to handle large
datasets, even on a puny laptop. You might want however to use h5py
instead of pytables. With the latter, it's a bit complicated in my
experience to get HDF5 libraries with support for the MPI standard.

Wishing you all the best in your scientific and programming endeavors,

Gregory
